name: Pull Request Stats

on: pull_request

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "$PR_STATS_TOKEN" > key'
         shell: bash
         env:
         PR_STATS_TOKEN: ${{secrets. PR_STATS_TOKEN}}
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          token: ${{secrets.PR_STATS_TOKEN}}
          slack-webhook: ${{secrets.PR_STATS_SLACK_WEBHOOK}}
          sort-by: 'REVIEWS'
          slack-channel: '#reviews'
          period: 15
